version: '3'
services:
    db:
      container_name: postgres_db
      image: postgres:latest
      restart: always
      environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
      volumes:
        - ./data:/var/lib/postgresql/data
        - ./schemas/init.sql:/docker-entrypoint-initdb.d/init.sql
      logging:
        driver: 'json-file'
        options:
          max-size: '10m'
          max-file: '10'
      ports:
        - "5432:5432"

    app:
      build: .
      ports:
        - "8080:8080"
      env_file:
        - .env
      environment:
        STAGE: ${STAGE}
        API_PORT: ${API_PORT}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_NAME: ${DB_NAME}
      volumes:
        - .:/app
      logging:
        driver: 'json-file'
        options:
          max-size: '10m'
          max-file: '10'
      depends_on:
        - db
#        - cache_db

#    cache_db:
#      container_name: redis_cache_db
#      image: redis
#      command: redis-server
#      restart: always
#      ports:
#        - "6379:6379"
